spring:
  application:
    name: actuator

management:
  server:
    port: 8080
    base-path: /actuator
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full

  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-components: always
      # show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Actuator Example
    company: Example Corp
    description: A simple Spring Boot application to demonstrate actuator endpoints.
    version: 1.0.0

logging:
  level:
   study.actuator.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true